name: DevSecOps CI/CD pipeline

on: [push]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: SAST - npm audit
      run: npm audit || true

    - name: SCA - Trivy filesystem scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .

    - name: Pull Juice Shop Docker image
      run: docker pull bkimminich/juice-shop

    - name: Container Scan - Trivy image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: bkimminich/juice-shop
        severity: HIGH,CRITICAL
      continue-on-error: true
